### PR TITLE
Update Hangman.

### PR DESCRIPTION
**Pull request by Animesh-Ghosh**
Issue #3.

Moved from DOS-style C++ to more modern standards using STL and containers to make life easier.

Also separated **`Hangman.cpp`** into three different files.

Renamed some functions to better reflect their purpose.

Heavily commented.

### CODE REVIEW

**Comment by adarshme** [comment]
I will go through the code and test it. Sorry for the late reply.

**Comment by adarshme** [comment]
There are 2 major bugs with this code:

1. If the user accidentally enters a letter again it is counted as multiple guesses and not one. This leads to wastage of the precious few attempts.
2. The round should end when there are no guesses left. The guess counter is broken (displays negative turns left after all 7 guesses are exhausted).

**Comment by Animesh-Ghosh** [comment]
Have tried to fix the bugs in the new commit.

**Comment by Animesh-Ghosh** [comment]
Hey @InfernoCoder11, can you please review? 😅

**Comment by adarshme** [comment]
Yes of course. Thanks a lot for your efforts. Much appreciated.

P.S. - I didn't get a notification for your earlier comment and had totally forgot about this. Sorry for being so late.

**Pull request merged**
